// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ClassBar: typeof import('./src/components/classBar.vue')['default']
    copy: typeof import('./src/components/majorBar copy.vue')['default']
    CourseBar: typeof import('./src/components/courseBar.vue')['default']
    CourseLine: typeof import('./src/components/courseLine.vue')['default']
    CourseLine1: typeof import('./src/components/courseLine1.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElR: typeof import('element-plus/es')['ElR']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRo: typeof import('element-plus/es')['ElRo']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ExcellentBar: typeof import('./src/components/excellentBar.vue')['default']
    ExcellentLine: typeof import('./src/components/excellentLine.vue')['default']
    ExcellentLine1: typeof import('./src/components/excellentLine1.vue')['default']
    GradeBar: typeof import('./src/components/gradeBar.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    MajorBar: typeof import('./src/components/majorBar.vue')['default']
    MajorBar1: typeof import('./src/components/majorBar1.vue')['default']
    Proportion: typeof import('./src/components/proportion.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreBar: typeof import('./src/components/scoreBar.vue')['default']
    Sidebar: typeof import('./src/components/sidebar.vue')['default']
    StudentInfoBar: typeof import('./src/components/studentInfoBar.vue')['default']
    Tags: typeof import('./src/components/tags.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
