"""2 commit

Revision ID: cbcd903a3a34
Revises: 832832c4e8b2
Create Date: 2022-08-27 10:30:10.752966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbcd903a3a34'
down_revision = '832832c4e8b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('courseName', sa.String(length=30), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('courseName', 'term')
    )
    op.create_table('excellentStudyClass',
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('totalClassNum', sa.Integer(), nullable=True),
    sa.Column('excellentClassNum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('grade', 'year')
    )
    op.create_table('scores',
    sa.Column('stuID', sa.String(length=10), nullable=False),
    sa.Column('courseName', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('term', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('stuID', 'courseName')
    )
    op.create_table('stuanalysis',
    sa.Column('stuID', sa.String(length=10), nullable=False),
    sa.Column('stuName', sa.String(length=20), nullable=False),
    sa.Column('stuType', sa.Integer(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('failSubjectName', sa.String(length=200), nullable=True),
    sa.Column('stuClass', sa.String(length=10), nullable=True),
    sa.Column('content1', sa.String(length=850), nullable=True),
    sa.Column('content2', sa.String(length=850), nullable=True),
    sa.Column('content3', sa.String(length=850), nullable=True),
    sa.PrimaryKeyConstraint('stuID', 'stuType', 'term')
    )
    op.create_table('teachers',
    sa.Column('tID', sa.String(length=8), nullable=False),
    sa.Column('tCourse', sa.String(length=20), nullable=False),
    sa.Column('tClass', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('tID')
    )
    op.create_table('user',
    sa.Column('cID', sa.String(length=10), nullable=False, comment='工号'),
    sa.Column('cName', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('cID', 'cName')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('teachers')
    op.drop_table('stuanalysis')
    op.drop_table('scores')
    op.drop_table('excellentStudyClass')
    op.drop_table('courses')
    # ### end Alembic commands ###
