"""file commit

Revision ID: cd3038557213
Revises: cbcd903a3a34
Create Date: 2022-08-29 23:28:19.566901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd3038557213'
down_revision = 'cbcd903a3a34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('filedb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fileName', sa.String(length=40), nullable=False),
    sa.Column('md5', sa.String(length=10), nullable=False),
    sa.Column('owner_id', sa.String(length=10), nullable=False),
    sa.Column('fileType', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filedb_id'), 'filedb', ['id'], unique=False)
    op.create_table('students',
    sa.Column('stuID', sa.String(length=10), nullable=False),
    sa.Column('stuName', sa.String(length=20), nullable=False),
    sa.Column('stuClass', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('stuID')
    )
    op.drop_table('excellentstudyclass')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('students')
    op.drop_index(op.f('ix_filedb_id'), table_name='filedb')
    op.drop_table('filedb')
    op.drop_table('excellentStudyClass')
    # ### end Alembic commands ###
